version: '3.9'

services:
  # vue-server:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #     target: dev  # Use the dev-stage from the Dockerfile
  #   ports:
  #     - "5173:5173"  # Expose development port
  #   volumes:
  #     - ./client/:/app  # Mount code for live-reloading
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - chefNet
  chefbook-server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    networks:
      - chefNet
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - images:/app/imgs
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest  
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    volumes:
    - sqlserver_data:/var/opt/mssql
    networks:
      - chefNet
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - chefNet
networks:
  chefNet:
    name: chefNet
    driver: bridge 

volumes:
  sqlserver_data:
    driver: local
  images:
    driver: local        