version: '3.9'

services:
  chefbook-server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    networks:
      - chefNet
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - images:/app/imgs
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest  
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    volumes:
    - sqlserver_data:/var/opt/mssql
    networks:
      - chefNet

networks:
  chefNet:
    name: chefNet
    driver: bridge 

volumes:
  sqlserver_data:
    driver: local
  images:
    driver: local        